# Copyright (c) 2008 by 2008 Model Driven Development sl and Antonio Carrasco Valero
#
# GNU General Public License (GPL)
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.
#

return [ 

    {   'portal_types':             ['ReferenciaCualificada', ],
        'config_name':               'Mention',
        'mode':                     'Reference',
        'extension':                'OneParagraph',
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],   
    },
    {   'portal_types':             ['ReferenciaCualificada', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
            ['text',                'Text',        'HideLabel',   'Optional',], 
        ],
        'traversals': [
            {   'relation_name':            'referidosCualificados',
                'related_types': [
                    {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                        'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
        ],  
    },
    {   'portal_types':             ['PoliticaDeNegocio', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [
            ['title',               'String',      'Title', ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],   
    },
    {   'portal_types':             ['PoliticaDeNegocio', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
            ['text',                'Text',        'HideLabel',   'Optional',], 
            ['codigo',              'String',      'Optional',], 
            ['estado',              'String',      'Optional',], 
            ['nivelDeImposicion',   'String',      'Optional',], 
            ['version',             'String',      'Optional',], 
            ['fechaAdopcion',       'Date',        'Optional',], 
            ['fechaObsolescencia',  'Date',        'Optional',], 
        ],
       'traversals': [
             {   'subitems': [
                    {   'portal_types':         ['ColeccionPoliticasDeNegocio', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
             {   'relation_name':            'reglasDeNegocioDerivadas',
                 'dependency':                      'Supplier',
                 'related_types': [
                     {   'portal_types':             ['ReglaDeNegocio', ],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             }, 
             {   'relation_name':            'procesosDeNegocioGobernados',
                 'dependency':                      'Supplier',
                 'related_types': [
                     {   'portal_types':             ['ProcesoDeNegocioSimple', ],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             }, 
             {   'relation_name':            'participantesGobernados',
                 'dependency':                      'Supplier',
                 'related_types': [
                     {   'portal_types':             ['UnidadOrganizacional', 'Perfil', ],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             }, 
             {   'relation_name':            'herramientasGobernadas',
                 'dependency':                      'Supplier',
                 'related_types': [
                     {   'portal_types':             ['Herramienta', ],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             }, 
             {   'relation_name':            'artefactosGobernados',
                 'dependency':                      'Supplier',
                 'related_types': [
                     {   'portal_types':             ['Artefacto', ],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             }, 
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],   
    },
    {   'portal_types':             ['ReglaDeNegocio', ],
        'config_name':               'Mention',
        'mode':                     'Reference',
        'extension':                'OneParagraph',
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],   
    },
    {   'portal_types':             ['ReglaDeNegocio', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
            ['text',                'Text',        'HideLabel',   'Optional',], 
            ['codigo',              'String',      'Optional',], 
            ['estado',              'String',      'Optional',], 
            ['nivelDeImposicion',   'String',      'Optional',], 
            ['version',             'String',      'Optional',], 
            ['fechaAdopcion',       'Date',        'Optional',], 
            ['fechaObsolescencia',  'Date',        'Optional',], 
        ],
        'traversals': [
            {   'subitems': [
                    {   'portal_types':         ['ColeccionReglasDeNegocio', ],
                        'reuse_config':         'Default',
                    },
                 ],
            },
            {   'relation_name':            'politicasDeNegocioBase',
                'related_types': [
                    {   'portal_types':             ['PoliticaDeNegocio', ],
                        'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'procesosDeNegocioDirigidos',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'pasosAplicandoLaRegla',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'participantesDirigidos',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['UnidadOrganizacional', 'Perfil', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'artefactosDirigidos',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['Artefacto', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'herramientasDirigidas',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['Herramienta', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
              {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
       ],  
    },
    {   'portal_types':                 ['UnidadOrganizacional', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',], 
        ],   
    },
    {   'portal_types':                 ['UnidadOrganizacional', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',], 
            ['text',                    'Text',        'HideLabel',   'Optional',], 
            ['abreviatura',             'String',      'Optional',], 
            ['responsabilidadesClave',  'Text',      'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                   { 'portal_types':          ['ColeccionUnidadesOrganizacionales',],
                         'reuse_config':         'Default',
                     },
                ],
             },
             {   'subitems': [
                    { 'portal_types':         ['ColeccionPerfiles', ],
                        'reuse_config':         'Default',
                    },
                ],
             },
            {   'relation_name':            'procesosEjecutados',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'pasosEjecutados',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'destinatarioDeEnvios',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['Envio', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'remitenteDeRecepciones',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['Recepcion', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'procesosSupervisados',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'responsableDeArtefactos',
                'related_types': [
                    {   'portal_types':             ['Artefacto', ],
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'responsableDeHerramientas',
                'related_types': [
                    {   'portal_types':             ['Herramienta', ],
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'afectadoPorReglasDeNegocio',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'afectadoPorPoliticasDeNegocio',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PoliticaDeNegocio', ],
                        'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':                 ['Perfil', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [
            ['title',                   'String',    'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',      'Description', 'Optional',], 
        ],   
    },
    {   'portal_types':                 ['Perfil', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',                   'String',    'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',      'Description', 'Optional',], 
            ['text',                    'Text',      'HideLabel',   'Optional',] ,
            ['abreviatura',             'String',    'Optional',], 
            ['responsabilidadesClave',  'Text',      'Optional',], 
            ['conocimientosPoseidos',   'Text',      'Optional',], 
            ['habilidadesDemostradas',  'Text',      'Optional',], 
            ['seleccionDePersonal',     'Text',      'Optional',], 
        ],
        'traversals': [
            {   'relation_name':            'procesosEjecutados',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'pasosEjecutados',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'destinatarioDeEnvios',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['Envio', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'remitenteDeRecepciones',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['Recepcion', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'procesosSupervisados',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'responsableDeArtefactos',
                'related_types': [
                    {   'portal_types':             ['Artefacto', ],
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'responsableDeHerramientas',
                'related_types': [
                    {   'portal_types':             ['Herramienta', ],
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
            {   'relation_name':            'afectadoPorPoliticasDeNegocio',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PoliticaDeNegocio', ],
                        'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'afectadoPorReglasDeNegocio',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
       ],  
    },
    {   'portal_types':             ['Artefacto', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',], 
        ],   
    },
    {   'portal_types':             ['Artefacto', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',], 
            ['text',                    'Text',        'HideLabel',   'Optional',], 
            ['codigo',                  'String',      'Optional',], 
            ['estado',                  'String',      'Optional',], 
            ['nivelDeImposicion',       'String',      'Optional',], 
            ['version',                 'String',      'Optional',], 
            ['fechaAdopcion',           'Date',        'Optional',], 
            ['fechaObsolescencia',      'Date',        'Optional',], 
        ],
        'traversals': [
            {   'relation_name':            'responsablesDeArtefacto',
                'related_types': [
                    {   'portal_types':         ['UnidadOrganizacional', 'Perfil',  ],
                        'reuse_config':         'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'herramientas',
                'related_types': [
                    {   'portal_types':         ['Herramienta',  ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':         'Mention',
                    },
                ],
           },                        
             {   'subitems': [
                    {   'portal_types':         ['ColeccionArtefactos', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
            {   'relation_name':            'entradasAProcesosDeNegocio',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':         ['Entrada',  ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':         'Mention',
                    },
                ],
           },                        
            {   'relation_name':            'salidasDeProcesosDeNegocio',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':         ['Salida',  ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':         'Mention',
                    },
                ],
           },                        
            {   'relation_name':            'pasosQueRecibenElArtefacto',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
           },                        
            {   'relation_name':            'pasosQueEnvianElArtefacto',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
           },                        
            {   'relation_name':            'afectadoPorPoliticasDeNegocio',
                'related_types': [
                    {   'portal_types':             ['PoliticaDeNegocio', ],
                        'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'afectadoPorReglasDeNegocio',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },    
    {   'portal_types':             ['Herramienta', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',], 
        ],   
    },
    {   'portal_types':             ['Herramienta', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',], 
            ['text',                    'Text',        'HideLabel',   'Optional',], 
            ['codigo',                  'String',      'Optional',], 
            ['estado',                  'String',      'Optional',], 
            ['nivelDeImposicion',       'String',      'Optional',], 
            ['version',                 'String',      'Optional',], 
            ['fechaAdopcion',           'Date',        'Optional',], 
            ['fechaObsolescencia',      'Date',        'Optional',], 
        ],
        'traversals': [
            {   'relation_name':            'responsablesDeHerramienta',
                'related_types': [
                    {   'portal_types':         ['UnidadOrganizacional', 'Perfil',  ],
                        'reuse_config':         'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'artefactosDeHerramienta',
                'related_types': [
                    {   'portal_types':         ['Artefacto',  ],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':         'Mention',
                    },
                ],
           },                        
            {   'relation_name':            'pasosAsistidos',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
           },                        
            {   'relation_name':            'pasosQueEnvianElArtefacto',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
           },                        
            {   'relation_name':            'pasosQueRecibenElArtefacto',
                 'dependency':                      'Supplier',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
           },                        
            {   'relation_name':            'afectadaPorPoliticasDeNegocio',
                'related_types': [
                    {   'portal_types':             ['PoliticaDeNegocio', ],
                        'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'afectadaPorReglasDeNegocio',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ]
            },                        
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },    
    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
            ['codigo',              'String',      'Optional',], 
        ],   
    },
    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
            ['codigo',                                     'String',      'Optional',], 
            ['estado',                                     'String',      'Optional',], 
            ['nivelDeImposicion',                          'String',      'Optional',], 
            ['version',                                    'String',      'Optional',], 
            ['fechaAdopcion',                              'Date',        'Optional',], 
            ['fechaObsolescencia',                         'Date',        'Optional',], 
            ['responsableMantenimiento',                   'String',      'Optional',], 
            ['requierePlanificacion',                      'Boolean',      'Optional',], 
            ['esRepetible',                                'Boolean',      'Optional',],  
            ['esContinuo',                                 'Boolean',      'Optional',],                     
            ['proposito',                                  'Text',        'Optional',],                     
            ['seleccionDePersonal',                        'Text',        'Optional',],                     
            ['preCondicion',                               'Text',        'Optional',],                     
            ['postCondicion',                              'Text',        'Optional',],                     
        ],
        'traversals': [
            {   'relation_name':            'supervisor',
                'related_types': [
                    {   'portal_types':             ['Perfil', 'UnidadOrganizacional', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'ejecutores',
                'related_types': [
                    {   'portal_types':             ['Perfil', 'UnidadOrganizacional', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
             {   'subitems': [
                     { 'portal_types':         ['ColeccionEntradas',],
                         'reuse_config':         'Default',
                    },
                 ],
             },   
             {   'subitems': [
                    { 'portal_types':         ['ColeccionSalidas',],
                        'reuse_config':         'Default',
                    },
                 ],
             },   
             {   'subitems': [
                    { 'portal_types':         ['ColeccionPasos',],
                        'reuse_config':         'Default',
                    },
                 ],
             },   
             {   'subitems': [
                    {   'portal_types':         ['ColeccionProcesosDeNegocio', ],
                        'reuse_config':         'Default',
                    },
                 ],
             }, 
            {   'relation_name':            'politicasDeNegocioGobernantes',
                'related_types': [
                    {   'portal_types':             ['PoliticaDeNegocio', ],
                        'if_not_included':          'NotInAnnex',
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'reglasDeNegocioDirigentes',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'usadoComoSubProcesos',
                'related_types': [
                    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':             ['Entrada', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [
            ['title',  'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],   
    },
    {   'portal_types':             ['Entrada', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
            ['text',                'Text',        'HideLabel',   'Optional',], 
            ['esRequerido',         'Boolean',     'Optional',], 
            ['fuenteDeInformacion', 'Text',        'Optional',], 
            ['valorDefecto',        'Text',        'Optional',], 
        ],
        'traversals': [
            {   'relation_name':            'artefactosDeEntrada',
                'related_types': [
                    {   'portal_types':             ['Artefacto', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':             ['Salida', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [
            ['title',  'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],  
    },
    {   'portal_types':             ['Salida', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [
            ['title',               'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
            ['text',                'Text',        'HideLabel',   'Optional',], 
            ['esRequerido',         'Boolean',     'Optional',], 
        ],
        'traversals': [
            {   'relation_name':            'artefactosDeSalida',
                'related_types': [
                    {   'portal_types':             ['Artefacto', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':    [ 'ExitoFinal', 'FracasoFinal', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [ 
            ['title',  'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
        ],   
    },
    {   'portal_types':    [ 'ExitoFinal', 'FracasoFinal', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [ 
            ['title',                   'String',      'Title',], 
            ['numeroDePaso',            'Number',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
            ['text',                    'Text',        'HideLabel', 'Optional',] ,
        ],
        'traversals': [
            {   'relation_name':            'reglasDeNegocioAplicadas',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                                                                
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':    [ 'PasoSimple',],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [ 
            ['title',                   'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['numeroDePaso',            'Number',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
        ],   
    },
    {   'portal_types':    [ 'PasoSimple',],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [ 
            ['title',  'String',        'Title',], 
            ['archetype_name',          'String',      'Meta',        'Class', 'Glossary',], 
            ['numeroDePaso',            'Number',      ], 
            ['description',             'Text',        'Description', 'Optional',],                                         
            ['text',                    'Text',        'HideLabel', 'Optional',], 
        ],
        'traversals': [
            {   'relation_name':            'ejecutoresDelPaso',
                'related_types': [
                    {   'portal_types':             ['Perfil', 'UnidadOrganizacional', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'herramientasAplicadas',
                'related_types': [
                    {   'portal_types':             ['Herramienta', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'reglasDeNegocioAplicadas',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                                                                
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':    [ 'Decision' , ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [ 
            ['title',  'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
        ],   
    },
    {   'portal_types':    [ 'Decision' , ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [ 
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['numeroDePaso',            'Number',      ], 
            ['description',             'Text',        'Description', 'Optional',],                                         
            ['text',                    'Text',        'HideLabel', 'Optional',] ,
        ],                                        
        'traversals': [
            {   'relation_name':            'siTrue',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'siFalse',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'ejecutoresDelPaso',
                'related_types': [
                    {   'portal_types':             ['Perfil', 'UnidadOrganizacional', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'herramientasAplicadas',
                'related_types': [
                    {   'portal_types':             ['Herramienta', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'reglasDeNegocioAplicadas',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                                                                
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':    [ 'SubProceso', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [ 
            ['title',  'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
        ],   
    },
    {   'portal_types':    [ 'SubProceso', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [ 
            ['title',                   'String',      'Title',], 
            ['numeroDePaso',            'Number',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
            ['text',                    'Text',        'HideLabel', 'Optional',] ,
        ],
        'traversals': [
            {   'relation_name':            'procesoUsado',
                'related_types': [
                    {   'portal_types':             ['ProcesoDeNegocioSimple', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'reglasDeNegocioAplicadas',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                                                                
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':    [ 'Envio', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [ 
            ['title',  'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
        ],   
    },
    {   'portal_types':    [ 'Envio', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [ 
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['numeroDePaso',            'Number',      ], 
            ['description',             'Text',        'Description', 'Optional',],                                         
            ['text',                    'Text',        'HideLabel', 'Optional',] ,
        ],
        'traversals': [
            {   'relation_name':            'destinatarios',
                'related_types': [
                    {   'portal_types':             ['Perfil', 'UnidadOrganizacional', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'artefactosEnviados',
                'related_types': [
                    {   'portal_types':             ['Artefacto', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'ejecutoresDelPaso',
                'related_types': [
                    {   'portal_types':             ['Perfil', 'UnidadOrganizacional', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'herramientasAplicadas',
                'related_types': [
                    {   'portal_types':             ['Herramienta', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'reglasDeNegocioAplicadas',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                                                                
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':    [ 'Recepcion', ],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'attrs': [ 
            ['title',  'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
        ],   
    },
    {   'portal_types':    [ 'Recepcion', ],
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', ],
        'attrs': [ 
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['numeroDePaso',            'Number',      ], 
            ['description',             'Text',        'Description', 'Optional',],                                         
            ['text',                    'Text',        'HideLabel', 'Optional',] ,
        ],
        'traversals': [
            {   'relation_name':            'remitente',
                'related_types': [
                    {   'portal_types':             ['Perfil', 'UnidadOrganizacional', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'artefactosRecibidos',
                'related_types': [
                    {   'portal_types':             ['Artefacto', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'ejecutoresDelPaso',
                'related_types': [
                    {   'portal_types':             ['Perfil', 'UnidadOrganizacional', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'herramientasAplicadas',
                'related_types': [
                    {   'portal_types':             ['Herramienta', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'reglasDeNegocioAplicadas',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                                                                
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
              {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
       ],  
    },
    {   'portal_types':    [ 'Plazo',],
        'config_name':               'Mention',
        'extension':                'OneParagraph',
        'mode':                     'Reference',
        'divider':                  [ 'Before', 'White',],
        'attrs': [ 
            ['title',  'String',      'Title',], 
            ['tituloDelContenedor',     'String',      ], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',             'Text',        'Description', 'Optional',],                                         
        ],   
    },
    {   'portal_types':    [ 'Plazo',],
        'extension':                'NonTextAttrsOneParagraph',
        'attrs': [ 
            ['title',                   'String',      'Title',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['numeroDePaso',            'Number',      ], 
            ['description',             'Text',        'Description', 'Optional',],                                         
            ['text',                    'Text',        'HideLabel', 'Optional',] ,
        ],                                       
        'traversals': [
            {   'relation_name':            'comienzaEnPaso',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision',  'SubProceso', 'Envio', 'Recepcion', 'Plazo', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'pasoRequerido',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'SubProceso', 'Envio', 'Recepcion',  ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'pasoTrasSatisfaccionRequeridos',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'pasoTrasExpiracion',
                'related_types': [
                    {   'portal_types':             ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                        
            {   'relation_name':            'reglasDeNegocioAplicadas',
                'related_types': [
                    {   'portal_types':             ['ReglaDeNegocio', ],
                        'reuse_config':             'Mention',
                    },
                ],
            },                                                                
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],  
    },
    {   'portal_types':     ['ColeccionPoliticasDeNegocio', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['PoliticaDeNegocio',],
                       'reuse_config':          'Default',
                    },
                 ],
             },   
        ],
    },
    {   'portal_types':     ['ColeccionReglasDeNegocio', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['ReglaDeNegocio',],
                         'reuse_config':         'Default',
                    },
                 ],
             },                       
        ],
    },
    {   'portal_types':     ['ColeccionUnidadesOrganizacionales', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['UnidadesOrganizacional', 'Perfil',],
                         'reuse_config':         'Default',
                    },
                 ],
             },   
        ],
    },
    {   'portal_types':     ['ColeccionPerfiles', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['Perfil',],
                         'reuse_config':         'Default',
                    },
                 ],
             },   
        ],
    },
    {   'portal_types':     ['ColeccionProcesosDeNegocio', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['ProcesoDeNegocioSimple',],
                         'reuse_config':         'Default',
                    },
                 ],
             },   
        ],
    },
    {   'portal_types':     ['ColeccionEntradas', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['Entrada',],
                         'reuse_config':         'Default',
                    },
                 ],
             },   
        ],
    },
    {   'portal_types':     ['ColeccionSalidas', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['Salida',],
                         'reuse_config':         'Default',
                    },
                 ],
             },   
        ],
    },   
    {   'portal_types':     ['ColeccionPasos', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo', ],
                         'reuse_config':        'Default',
                    },
                 ],
             },   
        ],
    },   
    {   'portal_types':     ['ColeccionArtefactos', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['Artefacto',],
                         'reuse_config':         'Default',
                    },
                 ],
             },   
        ],
    },
    {   'portal_types':     ['ColeccionHerramientas', ],
        'conditions':       ['ObjectValuesNotEmpty'],
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
            ['title',               'String',      'Title',       'Translate',], 
            ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
            ['description',         'Text',        'Description', 'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                     { 'portal_types':         ['Herramienta',],
                         'reuse_config':         'Default',
                    },
                 ],
             },   
        ],
    },
    {   'portal_types':    ['Organizacion',], 
        'extension':                'NonTextAttrsOneParagraph',
        'divider':                  [ 'Before', 'Always','White',],
        'attrs': [
             ['title',               'String',      'Title',], 
             ['archetype_name',      'String',      'Meta',        'Class', 'Glossary',], 
             ['description',         'Text',        'Description', 'Optional',], 
             ['text',                'Text',        'HideLabel',   'Optional',], 
             ['abreviatura',         'String',      'Optional',], 
        ],
        'traversals': [
             {   'subitems': [
                    {   'portal_types':         ['ColeccionProcesosDeNegocio', ],
                        'reuse_config':         'Default',
                    },
                 ],
             }, 
             {   'subitems': [
                    {   'portal_types':         ['ColeccionReglasDeNegocio', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
             {   'subitems': [
                    {   'portal_types':         ['ColeccionPerfiles', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
             {   'subitems': [
                    {   'portal_types':         ['ColeccionUnidadesOrganizacionales', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
             {   'subitems': [
                    {   'portal_types':         ['ColeccionArtefactos', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
             {   'subitems': [
                    {   'portal_types':         ['ColeccionHerramientas', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
             {   'subitems': [
                    {   'portal_types':         ['ColeccionPoliticasDeNegocio', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
             {   'relation_name':            'referidos',
                 'exclude_from_views':        ['Tabular', 'Textual', ],
                 'related_types': [
                     {   'portal_types':             ['Organizacion', 'PoliticaDeNegocio', 'ReglaDeNegocio', 'ProcesoDeNegocioSimple', 'Artefacto', 'Herramienta','Entrada', 'Salida', 'PasoSimple', 'Decision', 'ExitoFinal', 'FracasoFinal', 'SubProceso', 'Envio', 'Recepcion', 'Plazo',],
                         'if_not_included':          'NotInAnnex',
                         'reuse_config':             'Mention',
                     },
                 ],
             },                        
             {   'subitems': [
                    {   'portal_types':         ['ATLink', ],
                        'exclude_from_views':   ['Tabular', 'Textual', ],
                        'reuse_config':         'Default',
                    },
                 ],
             },
        ],
    },
]
